### ISSUE TITLE
Accept URL without a valid host

### ISSUE THREAD

**Issue by TetianaPerinha** [Sunagatov/Registry_Server#4]
The system accepts POST request to shortening link URL without a valid host.

**Step to reproduce:**
create a POST request as below 
curl --location 'https://short-link.zufargroup.com/api/v1/shorten' \
--header 'Content-Type: application/json' \
--data '{"originalUrl": "http://.com"}
'

**Expected result:** The system should reject the URL and return an error message indicating that the URL must have a valid host.

**Actual result:** The system accepts the URL without a valid host and generates a short link
<img width="1168" alt="URL without a valid host" src="https://github.com/user-attachments/assets/771071b0-9b6a-4b64-9745-a60025c79ec7">

**Comment by ilsinyakov** [comment]
Fixed
